### ISSUE TITLE
Countdown Line modification?

### ISSUE THREAD

**Issue by iamevl** [bugsounet/MMM-Pir#86]
Not a bug - more a query

How the heck can i make the countdown bar thinner?
I have modified the MMM-PIR_SCREEN_BAR.Line in MMM-Pir.css to 10px but it made no difference. i cannot see anywhere else to change it.
On my countdown bar (set to top_bar) i have an overlap which looks a little messy and want to change that.

![pir](https://github.com/bugsounet/MMM-Pir/assets/41927264/1f0f36c1-82fe-4ff3-ad97-63d55f0ccdc9)

**Comment by bugsounet** [comment]
Hi, sorry for late response

in custom CSS

you can try this:
 * For font size (sample):

```css 
#MMM-PIR_SCREEN_BAR.Line {
    font-size: 10px;
}
```

* For size bar (sample):

```css
#MMM-PIR_SCREEN_BAR.Line > * {
    height: 2px;
}
```

Happy use,
@bugsounet
